services:
  postgres:
    image: postgres:16-alpine
    container_name: nexus-db
    environment:
      POSTGRES_DB: nexus_ledger
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: nexus-cache
    ports:
      - "6379:6379"